const countrys = [
  {
    id: 1,
    name: "Wallis and Futuna",
    capital: "Mata-Utu",
    population: 11750,
    flag: "https://flagcdn.com/wf.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 2,
    name: "Iceland",
    capital: "Reykjavik",
    population: 366425,
    flag: "https://flagcdn.com/is.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 3,
    name: "Luxembourg",
    capital: "Luxembourg",
    population: 632275,
    flag: "https://flagcdn.com/lu.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 4,
    name: "Mali",
    capital: "Bamako",
    population: 20250834,
    flag: "https://flagcdn.com/ml.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 5,
    name: "Comoros",
    capital: "Moroni",
    population: 869595,
    flag: "https://flagcdn.com/km.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 6,
    name: "Australia",
    capital: "Canberra",
    population: 25687041,
    flag: "https://flagcdn.com/au.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 7,
    name: "Estonia",
    capital: "Tallinn",
    population: 1331057,
    flag: "https://flagcdn.com/ee.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 8,
    name: "Canada",
    capital: "Ottawa",
    population: 38005238,
    flag: "https://flagcdn.com/ca.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 9,
    name: "Belarus",
    capital: "Minsk",
    population: 9398861,
    flag: "https://flagcdn.com/by.svg",
    isLike: false,
    isSave: false,
  },
  {
    id: 10,
    name: "Guyana",
    capital: "Georgetown",
    population: 786559,
    flag: "https://flagcdn.com/gy.svg",
    isLike: false,
    isSave: false,
  },
];
